[dev]
  command = "npm run dev" # Command to start your dev server
  targetPort = 3000 # The port for your application server, framework or site generator
  port = 8880 # The port that the netlify dev will be accessible on
  publish = "dist" # The path to your static content folder
  autoLaunch = true # a Boolean value that determines if Netlify Dev launches the local server address in your browser
  envFiles = [".env"] # The env files to use, ordered by priority (left - highest, right - lowest)
  # to start an https server instead of an http one, configure a certificate and key files
  # [dev.https]
  #  certFile = "cert.pem" # path to the certificate file
  #  keyFile = "key.pem" # path to the private key file

[build]
  command = "npm run build"
  publish = "/dist"
  base ="/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-DNS-Prefetch-Control = "on"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Opener-Policy = "same-origin-allow-popups"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Content-Security-Policy= '''
    default-src 'self' snrxmggiuferssrzuzwh.supabase.co;
    font-src 'self' fonts.googleapis.com fonts.gstatic.com;
    style-src 'self' fonts.googleapis.com fonts.gstatic.com;
    connect-src 'self' wss: fetch snrxmggiuferssrzuzwh.supabase.co;
    '''
